#ifndef REF0_PRESENT
#define REF0_PRESENT 0
#endif
#ifndef REF0_LABEL
#define REF0_LABEL 
#endif
#ifndef REF0_TYPE
#define REF0_TYPE 
#endif
#ifndef REF0_ESYNC
#define REF0_ESYNC 
#endif
#ifndef REF0_REFSYNC
#define REF0_REFSYNC 
#endif
#ifndef REF0_FREQS
#define REF0_FREQS 
#endif
#ifndef REF0P_PRESENT
#define REF0P_PRESENT 0
#endif
#ifndef REF0P_LABEL
#define REF0P_LABEL 
#endif
#ifndef REF0P_TYPE
#define REF0P_TYPE 
#endif
#ifndef REF0P_ESYNC
#define REF0P_ESYNC 
#endif
#ifndef REF0P_REFSYNC
#define REF0P_REFSYNC 
#endif
#ifndef REF0P_FREQS
#define REF0P_FREQS 
#endif
#ifndef REF0N_PRESENT
#define REF0N_PRESENT 0
#endif
#ifndef REF0N_LABEL
#define REF0N_LABEL 
#endif
#ifndef REF0N_TYPE
#define REF0N_TYPE 
#endif
#ifndef REF0N_ESYNC
#define REF0N_ESYNC 
#endif
#ifndef REF0N_REFSYNC
#define REF0N_REFSYNC 
#endif
#ifndef REF0N_FREQS
#define REF0N_FREQS 
#endif
#ifndef REF1_PRESENT
#define REF1_PRESENT 0
#endif
#ifndef REF1_LABEL
#define REF1_LABEL 
#endif
#ifndef REF1_TYPE
#define REF1_TYPE 
#endif
#ifndef REF1_ESYNC
#define REF1_ESYNC 
#endif
#ifndef REF1_REFSYNC
#define REF1_REFSYNC 
#endif
#ifndef REF1_FREQS
#define REF1_FREQS 
#endif
#ifndef REF1P_PRESENT
#define REF1P_PRESENT 0
#endif
#ifndef REF1P_LABEL
#define REF1P_LABEL 
#endif
#ifndef REF1P_TYPE
#define REF1P_TYPE 
#endif
#ifndef REF1P_ESYNC
#define REF1P_ESYNC 
#endif
#ifndef REF1P_REFSYNC
#define REF1P_REFSYNC 
#endif
#ifndef REF1P_FREQS
#define REF1P_FREQS 
#endif
#ifndef REF1N_PRESENT
#define REF1N_PRESENT 0
#endif
#ifndef REF1N_LABEL
#define REF1N_LABEL 
#endif
#ifndef REF1N_TYPE
#define REF1N_TYPE 
#endif
#ifndef REF1N_ESYNC
#define REF1N_ESYNC 
#endif
#ifndef REF1N_REFSYNC
#define REF1N_REFSYNC 
#endif
#ifndef REF1N_FREQS
#define REF1N_FREQS 
#endif
#ifndef REF2_PRESENT
#define REF2_PRESENT 0
#endif
#ifndef REF2_LABEL
#define REF2_LABEL 
#endif
#ifndef REF2_TYPE
#define REF2_TYPE 
#endif
#ifndef REF2_ESYNC
#define REF2_ESYNC 
#endif
#ifndef REF2_REFSYNC
#define REF2_REFSYNC 
#endif
#ifndef REF2_FREQS
#define REF2_FREQS 
#endif
#ifndef REF2P_PRESENT
#define REF2P_PRESENT 0
#endif
#ifndef REF2P_LABEL
#define REF2P_LABEL 
#endif
#ifndef REF2P_TYPE
#define REF2P_TYPE 
#endif
#ifndef REF2P_ESYNC
#define REF2P_ESYNC 
#endif
#ifndef REF2P_REFSYNC
#define REF2P_REFSYNC 
#endif
#ifndef REF2P_FREQS
#define REF2P_FREQS 
#endif
#ifndef REF2N_PRESENT
#define REF2N_PRESENT 0
#endif
#ifndef REF2N_LABEL
#define REF2N_LABEL 
#endif
#ifndef REF2N_TYPE
#define REF2N_TYPE 
#endif
#ifndef REF2N_ESYNC
#define REF2N_ESYNC 
#endif
#ifndef REF2N_REFSYNC
#define REF2N_REFSYNC 
#endif
#ifndef REF2N_FREQS
#define REF2N_FREQS 
#endif
#ifndef REF3_PRESENT
#define REF3_PRESENT 0
#endif
#ifndef REF3_LABEL
#define REF3_LABEL 
#endif
#ifndef REF3_TYPE
#define REF3_TYPE 
#endif
#ifndef REF3_ESYNC
#define REF3_ESYNC 
#endif
#ifndef REF3_REFSYNC
#define REF3_REFSYNC 
#endif
#ifndef REF3_FREQS
#define REF3_FREQS 
#endif
#ifndef REF3P_PRESENT
#define REF3P_PRESENT 0
#endif
#ifndef REF3P_LABEL
#define REF3P_LABEL 
#endif
#ifndef REF3P_TYPE
#define REF3P_TYPE 
#endif
#ifndef REF3P_ESYNC
#define REF3P_ESYNC 
#endif
#ifndef REF3P_REFSYNC
#define REF3P_REFSYNC 
#endif
#ifndef REF3P_FREQS
#define REF3P_FREQS 
#endif
#ifndef REF3N_PRESENT
#define REF3N_PRESENT 0
#endif
#ifndef REF3N_LABEL
#define REF3N_LABEL 
#endif
#ifndef REF3N_TYPE
#define REF3N_TYPE 
#endif
#ifndef REF3N_ESYNC
#define REF3N_ESYNC 
#endif
#ifndef REF3N_REFSYNC
#define REF3N_REFSYNC 
#endif
#ifndef REF3N_FREQS
#define REF3N_FREQS 
#endif
#ifndef REF4_PRESENT
#define REF4_PRESENT 0
#endif
#ifndef REF4_LABEL
#define REF4_LABEL 
#endif
#ifndef REF4_TYPE
#define REF4_TYPE 
#endif
#ifndef REF4_ESYNC
#define REF4_ESYNC 
#endif
#ifndef REF4_REFSYNC
#define REF4_REFSYNC 
#endif
#ifndef REF4_FREQS
#define REF4_FREQS 
#endif
#ifndef REF4P_PRESENT
#define REF4P_PRESENT 0
#endif
#ifndef REF4P_LABEL
#define REF4P_LABEL 
#endif
#ifndef REF4P_TYPE
#define REF4P_TYPE 
#endif
#ifndef REF4P_ESYNC
#define REF4P_ESYNC 
#endif
#ifndef REF4P_REFSYNC
#define REF4P_REFSYNC 
#endif
#ifndef REF4P_FREQS
#define REF4P_FREQS 
#endif
#ifndef REF4N_PRESENT
#define REF4N_PRESENT 0
#endif
#ifndef REF4N_LABEL
#define REF4N_LABEL 
#endif
#ifndef REF4N_TYPE
#define REF4N_TYPE 
#endif
#ifndef REF4N_ESYNC
#define REF4N_ESYNC 
#endif
#ifndef REF4N_REFSYNC
#define REF4N_REFSYNC 
#endif
#ifndef REF4N_FREQS
#define REF4N_FREQS 
#endif
#ifndef OUT0_PRESENT
#define OUT0_PRESENT 0
#endif
#ifndef OUT0_LABEL
#define OUT0_LABEL 
#endif
#ifndef OUT0_TYPE
#define OUT0_TYPE 
#endif
#ifndef OUT0_ESYNC
#define OUT0_ESYNC 
#endif
#ifndef OUT0_REFSYNC
#define OUT0_REFSYNC 
#endif
#ifndef OUT0_FREQS
#define OUT0_FREQS 
#endif
#ifndef OUT0P_PRESENT
#define OUT0P_PRESENT 0
#endif
#ifndef OUT0P_LABEL
#define OUT0P_LABEL 
#endif
#ifndef OUT0P_TYPE
#define OUT0P_TYPE 
#endif
#ifndef OUT0P_ESYNC
#define OUT0P_ESYNC 
#endif
#ifndef OUT0P_REFSYNC
#define OUT0P_REFSYNC 
#endif
#ifndef OUT0P_FREQS
#define OUT0P_FREQS 
#endif
#ifndef OUT0N_PRESENT
#define OUT0N_PRESENT 0
#endif
#ifndef OUT0N_LABEL
#define OUT0N_LABEL 
#endif
#ifndef OUT0N_TYPE
#define OUT0N_TYPE 
#endif
#ifndef OUT0N_ESYNC
#define OUT0N_ESYNC 
#endif
#ifndef OUT0N_REFSYNC
#define OUT0N_REFSYNC 
#endif
#ifndef OUT0N_FREQS
#define OUT0N_FREQS 
#endif
#ifndef OUT1_PRESENT
#define OUT1_PRESENT 0
#endif
#ifndef OUT1_LABEL
#define OUT1_LABEL 
#endif
#ifndef OUT1_TYPE
#define OUT1_TYPE 
#endif
#ifndef OUT1_ESYNC
#define OUT1_ESYNC 
#endif
#ifndef OUT1_REFSYNC
#define OUT1_REFSYNC 
#endif
#ifndef OUT1_FREQS
#define OUT1_FREQS 
#endif
#ifndef OUT1P_PRESENT
#define OUT1P_PRESENT 0
#endif
#ifndef OUT1P_LABEL
#define OUT1P_LABEL 
#endif
#ifndef OUT1P_TYPE
#define OUT1P_TYPE 
#endif
#ifndef OUT1P_ESYNC
#define OUT1P_ESYNC 
#endif
#ifndef OUT1P_REFSYNC
#define OUT1P_REFSYNC 
#endif
#ifndef OUT1P_FREQS
#define OUT1P_FREQS 
#endif
#ifndef OUT1N_PRESENT
#define OUT1N_PRESENT 0
#endif
#ifndef OUT1N_LABEL
#define OUT1N_LABEL 
#endif
#ifndef OUT1N_TYPE
#define OUT1N_TYPE 
#endif
#ifndef OUT1N_ESYNC
#define OUT1N_ESYNC 
#endif
#ifndef OUT1N_REFSYNC
#define OUT1N_REFSYNC 
#endif
#ifndef OUT1N_FREQS
#define OUT1N_FREQS 
#endif
#ifndef OUT2_PRESENT
#define OUT2_PRESENT 0
#endif
#ifndef OUT2_LABEL
#define OUT2_LABEL 
#endif
#ifndef OUT2_TYPE
#define OUT2_TYPE 
#endif
#ifndef OUT2_ESYNC
#define OUT2_ESYNC 
#endif
#ifndef OUT2_REFSYNC
#define OUT2_REFSYNC 
#endif
#ifndef OUT2_FREQS
#define OUT2_FREQS 
#endif
#ifndef OUT2P_PRESENT
#define OUT2P_PRESENT 0
#endif
#ifndef OUT2P_LABEL
#define OUT2P_LABEL 
#endif
#ifndef OUT2P_TYPE
#define OUT2P_TYPE 
#endif
#ifndef OUT2P_ESYNC
#define OUT2P_ESYNC 
#endif
#ifndef OUT2P_REFSYNC
#define OUT2P_REFSYNC 
#endif
#ifndef OUT2P_FREQS
#define OUT2P_FREQS 
#endif
#ifndef OUT2N_PRESENT
#define OUT2N_PRESENT 0
#endif
#ifndef OUT2N_LABEL
#define OUT2N_LABEL 
#endif
#ifndef OUT2N_TYPE
#define OUT2N_TYPE 
#endif
#ifndef OUT2N_ESYNC
#define OUT2N_ESYNC 
#endif
#ifndef OUT2N_REFSYNC
#define OUT2N_REFSYNC 
#endif
#ifndef OUT2N_FREQS
#define OUT2N_FREQS 
#endif
#ifndef OUT3_PRESENT
#define OUT3_PRESENT 0
#endif
#ifndef OUT3_LABEL
#define OUT3_LABEL 
#endif
#ifndef OUT3_TYPE
#define OUT3_TYPE 
#endif
#ifndef OUT3_ESYNC
#define OUT3_ESYNC 
#endif
#ifndef OUT3_REFSYNC
#define OUT3_REFSYNC 
#endif
#ifndef OUT3_FREQS
#define OUT3_FREQS 
#endif
#ifndef OUT3P_PRESENT
#define OUT3P_PRESENT 0
#endif
#ifndef OUT3P_LABEL
#define OUT3P_LABEL 
#endif
#ifndef OUT3P_TYPE
#define OUT3P_TYPE 
#endif
#ifndef OUT3P_ESYNC
#define OUT3P_ESYNC 
#endif
#ifndef OUT3P_REFSYNC
#define OUT3P_REFSYNC 
#endif
#ifndef OUT3P_FREQS
#define OUT3P_FREQS 
#endif
#ifndef OUT3N_PRESENT
#define OUT3N_PRESENT 0
#endif
#ifndef OUT3N_LABEL
#define OUT3N_LABEL 
#endif
#ifndef OUT3N_TYPE
#define OUT3N_TYPE 
#endif
#ifndef OUT3N_ESYNC
#define OUT3N_ESYNC 
#endif
#ifndef OUT3N_REFSYNC
#define OUT3N_REFSYNC 
#endif
#ifndef OUT3N_FREQS
#define OUT3N_FREQS 
#endif
#ifndef OUT4_PRESENT
#define OUT4_PRESENT 0
#endif
#ifndef OUT4_LABEL
#define OUT4_LABEL 
#endif
#ifndef OUT4_TYPE
#define OUT4_TYPE 
#endif
#ifndef OUT4_ESYNC
#define OUT4_ESYNC 
#endif
#ifndef OUT4_REFSYNC
#define OUT4_REFSYNC 
#endif
#ifndef OUT4_FREQS
#define OUT4_FREQS 
#endif
#ifndef OUT4P_PRESENT
#define OUT4P_PRESENT 0
#endif
#ifndef OUT4P_LABEL
#define OUT4P_LABEL 
#endif
#ifndef OUT4P_TYPE
#define OUT4P_TYPE 
#endif
#ifndef OUT4P_ESYNC
#define OUT4P_ESYNC 
#endif
#ifndef OUT4P_REFSYNC
#define OUT4P_REFSYNC 
#endif
#ifndef OUT4P_FREQS
#define OUT4P_FREQS 
#endif
#ifndef OUT4N_PRESENT
#define OUT4N_PRESENT 0
#endif
#ifndef OUT4N_LABEL
#define OUT4N_LABEL 
#endif
#ifndef OUT4N_TYPE
#define OUT4N_TYPE 
#endif
#ifndef OUT4N_ESYNC
#define OUT4N_ESYNC 
#endif
#ifndef OUT4N_REFSYNC
#define OUT4N_REFSYNC 
#endif
#ifndef OUT4N_FREQS
#define OUT4N_FREQS 
#endif
#ifndef OUT5_PRESENT
#define OUT5_PRESENT 0
#endif
#ifndef OUT5_LABEL
#define OUT5_LABEL 
#endif
#ifndef OUT5_TYPE
#define OUT5_TYPE 
#endif
#ifndef OUT5_ESYNC
#define OUT5_ESYNC 
#endif
#ifndef OUT5_REFSYNC
#define OUT5_REFSYNC 
#endif
#ifndef OUT5_FREQS
#define OUT5_FREQS 
#endif
#ifndef OUT5P_PRESENT
#define OUT5P_PRESENT 0
#endif
#ifndef OUT5P_LABEL
#define OUT5P_LABEL 
#endif
#ifndef OUT5P_TYPE
#define OUT5P_TYPE 
#endif
#ifndef OUT5P_ESYNC
#define OUT5P_ESYNC 
#endif
#ifndef OUT5P_REFSYNC
#define OUT5P_REFSYNC 
#endif
#ifndef OUT5P_FREQS
#define OUT5P_FREQS 
#endif
#ifndef OUT5N_PRESENT
#define OUT5N_PRESENT 0
#endif
#ifndef OUT5N_LABEL
#define OUT5N_LABEL 
#endif
#ifndef OUT5N_TYPE
#define OUT5N_TYPE 
#endif
#ifndef OUT5N_ESYNC
#define OUT5N_ESYNC 
#endif
#ifndef OUT5N_REFSYNC
#define OUT5N_REFSYNC 
#endif
#ifndef OUT5N_FREQS
#define OUT5N_FREQS 
#endif
#ifndef OUT6_PRESENT
#define OUT6_PRESENT 0
#endif
#ifndef OUT6_LABEL
#define OUT6_LABEL 
#endif
#ifndef OUT6_TYPE
#define OUT6_TYPE 
#endif
#ifndef OUT6_ESYNC
#define OUT6_ESYNC 
#endif
#ifndef OUT6_REFSYNC
#define OUT6_REFSYNC 
#endif
#ifndef OUT6_FREQS
#define OUT6_FREQS 
#endif
#ifndef OUT6P_PRESENT
#define OUT6P_PRESENT 0
#endif
#ifndef OUT6P_LABEL
#define OUT6P_LABEL 
#endif
#ifndef OUT6P_TYPE
#define OUT6P_TYPE 
#endif
#ifndef OUT6P_ESYNC
#define OUT6P_ESYNC 
#endif
#ifndef OUT6P_REFSYNC
#define OUT6P_REFSYNC 
#endif
#ifndef OUT6P_FREQS
#define OUT6P_FREQS 
#endif
#ifndef OUT6N_PRESENT
#define OUT6N_PRESENT 0
#endif
#ifndef OUT6N_LABEL
#define OUT6N_LABEL 
#endif
#ifndef OUT6N_TYPE
#define OUT6N_TYPE 
#endif
#ifndef OUT6N_ESYNC
#define OUT6N_ESYNC 
#endif
#ifndef OUT6N_REFSYNC
#define OUT6N_REFSYNC 
#endif
#ifndef OUT6N_FREQS
#define OUT6N_FREQS 
#endif
#ifndef OUT7_PRESENT
#define OUT7_PRESENT 0
#endif
#ifndef OUT7_LABEL
#define OUT7_LABEL 
#endif
#ifndef OUT7_TYPE
#define OUT7_TYPE 
#endif
#ifndef OUT7_ESYNC
#define OUT7_ESYNC 
#endif
#ifndef OUT7_REFSYNC
#define OUT7_REFSYNC 
#endif
#ifndef OUT7_FREQS
#define OUT7_FREQS 
#endif
#ifndef OUT7P_PRESENT
#define OUT7P_PRESENT 0
#endif
#ifndef OUT7P_LABEL
#define OUT7P_LABEL 
#endif
#ifndef OUT7P_TYPE
#define OUT7P_TYPE 
#endif
#ifndef OUT7P_ESYNC
#define OUT7P_ESYNC 
#endif
#ifndef OUT7P_REFSYNC
#define OUT7P_REFSYNC 
#endif
#ifndef OUT7P_FREQS
#define OUT7P_FREQS 
#endif
#ifndef OUT7N_PRESENT
#define OUT7N_PRESENT 0
#endif
#ifndef OUT7N_LABEL
#define OUT7N_LABEL 
#endif
#ifndef OUT7N_TYPE
#define OUT7N_TYPE 
#endif
#ifndef OUT7N_ESYNC
#define OUT7N_ESYNC 
#endif
#ifndef OUT7N_REFSYNC
#define OUT7N_REFSYNC 
#endif
#ifndef OUT7N_FREQS
#define OUT7N_FREQS 
#endif
#ifndef OUT8_PRESENT
#define OUT8_PRESENT 0
#endif
#ifndef OUT8_LABEL
#define OUT8_LABEL 
#endif
#ifndef OUT8_TYPE
#define OUT8_TYPE 
#endif
#ifndef OUT8_ESYNC
#define OUT8_ESYNC 
#endif
#ifndef OUT8_REFSYNC
#define OUT8_REFSYNC 
#endif
#ifndef OUT8_FREQS
#define OUT8_FREQS 
#endif
#ifndef OUT8P_PRESENT
#define OUT8P_PRESENT 0
#endif
#ifndef OUT8P_LABEL
#define OUT8P_LABEL 
#endif
#ifndef OUT8P_TYPE
#define OUT8P_TYPE 
#endif
#ifndef OUT8P_ESYNC
#define OUT8P_ESYNC 
#endif
#ifndef OUT8P_REFSYNC
#define OUT8P_REFSYNC 
#endif
#ifndef OUT8P_FREQS
#define OUT8P_FREQS 
#endif
#ifndef OUT8N_PRESENT
#define OUT8N_PRESENT 0
#endif
#ifndef OUT8N_LABEL
#define OUT8N_LABEL 
#endif
#ifndef OUT8N_TYPE
#define OUT8N_TYPE 
#endif
#ifndef OUT8N_ESYNC
#define OUT8N_ESYNC 
#endif
#ifndef OUT8N_REFSYNC
#define OUT8N_REFSYNC 
#endif
#ifndef OUT8N_FREQS
#define OUT8N_FREQS 
#endif
#ifndef OUT9_PRESENT
#define OUT9_PRESENT 0
#endif
#ifndef OUT9_LABEL
#define OUT9_LABEL 
#endif
#ifndef OUT9_TYPE
#define OUT9_TYPE 
#endif
#ifndef OUT9_ESYNC
#define OUT9_ESYNC 
#endif
#ifndef OUT9_REFSYNC
#define OUT9_REFSYNC 
#endif
#ifndef OUT9_FREQS
#define OUT9_FREQS 
#endif
#ifndef OUT9P_PRESENT
#define OUT9P_PRESENT 0
#endif
#ifndef OUT9P_LABEL
#define OUT9P_LABEL 
#endif
#ifndef OUT9P_TYPE
#define OUT9P_TYPE 
#endif
#ifndef OUT9P_ESYNC
#define OUT9P_ESYNC 
#endif
#ifndef OUT9P_REFSYNC
#define OUT9P_REFSYNC 
#endif
#ifndef OUT9P_FREQS
#define OUT9P_FREQS 
#endif
#ifndef OUT9N_PRESENT
#define OUT9N_PRESENT 0
#endif
#ifndef OUT9N_LABEL
#define OUT9N_LABEL 
#endif
#ifndef OUT9N_TYPE
#define OUT9N_TYPE 
#endif
#ifndef OUT9N_ESYNC
#define OUT9N_ESYNC 
#endif
#ifndef OUT9N_REFSYNC
#define OUT9N_REFSYNC 
#endif
#ifndef OUT9N_FREQS
#define OUT9N_FREQS 
#endif
